### ISSUE TITLE
Map not displaying

### ISSUE THREAD

**Issue by osfrance** [Wirecloud/map-viewer-widget#4]
Hi, I try to display map-viewer but I had this message in util.js : "Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys"

It's possible to use openstreetmap ?

Thanks,

**Comment by aarranz** [comment]
It's possible to use OSM by using this other [map widget based on openlayers](https://github.com/Wirecloud/ol3-map-widget). This widget supports OSM, WMS and other tile layers.

**Comment by osfrance** [comment]
Thanks for help aarranz !

**Comment by osfrance** [comment]
With map-viewer 2.5.8 it's work !
Thanks,

**Comment by arilwan** [comment]
@osfrance 
Can you please describe how you figure it out? I am having same issue here, please.
![Screenshot 2019-03-21 at 12 12 03](https://user-images.githubusercontent.com/42409395/54751574-463b8800-4bd3-11e9-908d-9d760b770179.png)

**Comment by eramax** [comment]
> @osfrance
> Can you please describe how you figure it out? I am having same issue here, please.
> ![Screenshot 2019-03-21 at 12 12 03](https://user-images.githubusercontent.com/42409395/54751574-463b8800-4bd3-11e9-908d-9d760b770179.png)

 I am facing the same issue, did you find a solution ?
Regards

**Comment by arilwan** [comment]
Use the latest version of map viewer widget (v 2.6.2). You also need to get a Google API key [here](https://developers.google.com/maps/documentation/javascript/get-api-key)
